name: Build, Test, Report aur Deploy

on:
  push:
    branches:
      - main # Jab main branch pe push ho, yeh chale

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Linux machine pe chale

    steps:
      # Code checkout karo
      - name: Checkout Code
        uses: actions/checkout@v3

      # Node.js setup karo
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Node version

      # Dependencies install karo
      - name: Install Dependencies
        run: npm install

      # Report banao
      - name: Generate Test Report
        run: npm run report

      # Email bhejo
      - name: Send Report Email
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }} # GitHub Secrets mein daalo
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }} # GitHub Secrets mein daalo
        run: npm run send-report

      # Build aur Deploy (Vercel example)
      - name: Deploy to Vercel
        run: npx vercel --prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }} # Vercel token secret mein
