name: Website Build aur Test

on:
  push:
    branches:
      - main # Jab main pe push ho
  pull_request: # PR pe bhi chale

jobs:
  build:
   runs-on: ubuntu-latest

   steps:
    - name: Checkout repo
      uses: actions/checkout@v4 


    - name: Setup node
      uses: actions/setup-node@v3
      with:
         node-version: '18'

      
    - name: Setup dependdency
      run: npm install


      
 

    - name: Build Website
      run: npm run build # Website build karo
      
    - name: Upload Build
      uses: actions/upload-artifact@v4 # Build upload karo
      with:
          name: website-build
          path: dist/ # Build folder upload karo 
         
      
      
